/******************************************************************************/
/****        Generated by IBExpert 2015.12.21.1 23/02/2024 18:33:21        ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Firebird\Firebird_3_0\fbclient.dll';

CREATE DATABASE 'C:\Desen\Delphi\crud-01\AvaliacaoDelphi\db\PESSOAS.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_PFISICA_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_PFISICA_ID TO 4;

CREATE GENERATOR GEN_PJURIDICA_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_PJURIDICA_ID TO 2;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE PFISICA (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(100) NOT NULL,
    CPF   VARCHAR(20) NOT NULL
);

CREATE TABLE PJURIDICA (
    ID        INTEGER NOT NULL,
    NOME      VARCHAR(100) NOT NULL,
    CNPJ      VARCHAR(20) NOT NULL,
    EMAIL     VARCHAR(100),
    TELEFONE  VARCHAR(20),
    CELULAR   VARCHAR(20),
    ENDERECO  VARCHAR(100),
    BAIRRO    VARCHAR(50),
    CIDADE    VARCHAR(50),
    UF        CHAR(2),
    CEP       CHAR(10)
);

CREATE TABLE VINCULO (
    ID_PFISICA    INTEGER NOT NULL,
    ID_PJURIDICA  INTEGER NOT NULL
);

INSERT INTO PFISICA (ID, NOME, CPF) VALUES (1, 'BELTRANO', '123456');
INSERT INTO PFISICA (ID, NOME, CPF) VALUES (2, 'PATO DONALD', '963');
INSERT INTO PFISICA (ID, NOME, CPF) VALUES (3, 'PLUTO', '321');

COMMIT WORK;

INSERT INTO PJURIDICA (ID, NOME, CNPJ, EMAIL, TELEFONE, CELULAR, ENDERECO, BAIRRO, CIDADE, UF, CEP) VALUES (1, 'PATETA', '98049498', 'pateta@disney.com', '9852', '8704', 'DISNEY', 'ORLANDO', '', 'MI', '98098794  ');
INSERT INTO PJURIDICA (ID, NOME, CNPJ, EMAIL, TELEFONE, CELULAR, ENDERECO, BAIRRO, CIDADE, UF, CEP) VALUES (2, 'ESQUELETO', '7890', '', '', '', '', '', '', '  ', '          ');

COMMIT WORK;



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE PFISICA ADD CONSTRAINT PK_PFISICA PRIMARY KEY (ID);
ALTER TABLE PJURIDICA ADD CONSTRAINT PK_PJURIDICA PRIMARY KEY (ID);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: PFISICA_BI */
CREATE TRIGGER PFISICA_BI FOR PFISICA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if ((new.id is null) or (new.id = 0))  then
    new.id = gen_id(gen_pfisica_id,1);
end
^

/* Trigger: PJURIDICA_BI */
CREATE TRIGGER PJURIDICA_BI FOR PJURIDICA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_pjuridica_id,1);
end
^
SET TERM ; ^

